-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Blog.Object.Post exposing (..)

import Blog.InputObject
import Blog.Interface
import Blog.Object
import Blog.Scalar
import Blog.ScalarCodecs
import Blog.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Blog.ScalarCodecs.Id Blog.Object.Post
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Blog.ScalarCodecs.codecs |> Blog.Scalar.unwrapCodecs |> .codecId |> .decoder)


title : SelectionSet String Blog.Object.Post
title =
    Object.selectionForField "String" "title" [] Decode.string


body : SelectionSet String Blog.Object.Post
body =
    Object.selectionForField "String" "body" [] Decode.string


author : SelectionSet String Blog.Object.Post
author =
    Object.selectionForField "String" "author" [] Decode.string


createdAt : SelectionSet Int Blog.Object.Post
createdAt =
    Object.selectionForField "Int" "createdAt" [] Decode.int
