-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Blog.Mutation exposing (..)

import Blog.InputObject
import Blog.Interface
import Blog.Object
import Blog.Scalar
import Blog.ScalarCodecs
import Blog.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreatePostRequiredArguments =
    { input : Blog.InputObject.PostInput }


createPost :
    CreatePostRequiredArguments
    -> SelectionSet decodesTo Blog.Object.Post
    -> SelectionSet decodesTo RootMutation
createPost requiredArgs object_ =
    Object.selectionForCompositeField "createPost" [ Argument.required "input" requiredArgs.input Blog.InputObject.encodePostInput ] object_ identity


type alias DeletePostRequiredArguments =
    { input : Blog.ScalarCodecs.Id }


deletePost :
    DeletePostRequiredArguments
    -> SelectionSet String RootMutation
deletePost requiredArgs =
    Object.selectionForField "String" "deletePost" [ Argument.required "input" requiredArgs.input (Blog.ScalarCodecs.codecs |> Blog.Scalar.unwrapEncoder .codecId) ] Decode.string
