-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Blog.ScalarCodecs exposing (..)

import Blog.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias Id =
    Blog.Scalar.Id


type alias Upload =
    Blog.Scalar.Upload


codecs : Blog.Scalar.Codecs Id Upload
codecs =
    Blog.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        , codecUpload = defaultCodecs.codecUpload
        }
